name: Windows RDP ARM

on: [workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-11-arm
    steps:
    - name: Enable RDP Service
      shell: pwsh
      run: |
        # 启用远程桌面服务
        Set-Service -Name TermService -StartupType Automatic -Status Running

    - name: Configure RDP Access
      shell: pwsh
      env:
        RDP_USER: runneradmin
        RDP_PASSWORD: ${{ secrets.rdpw }}
      run: |
        # 设置用户密码
        $securePass = ConvertTo-SecureString $env:RDP_PASSWORD -AsPlainText -Force
        Set-LocalUser -Name $env:RDP_USER -Password $securePass
        Enable-LocalUser -Name $env:RDP_USER
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $env:RDP_USER

        # 启用RDP服务
        Set-Service -Name TermService -StartupType Automatic -Status Running
        New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow
        
        # 启用账户并添加远程桌面组
        Enable-LocalUser -Name $env:TARGET_USER
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $env:TARGET_USER

    - name: Cloudflare
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/download/latest/cloudflared-windows-amd64.exe" -OutFile . -UseBasicParsing

    - name: Cloudflare run
      shell: cmd
      run: |
        ./cloudflared.exe tunnel --url tcp://localhost:3389
